# Generated by Django 3.1 on 2020-08-17 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20200807_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing_model',
            name='photo',
        ),
    ]
