# Generated by Django 3.1 on 2020-08-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_model_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing_model',
            name='phone',
            field=models.IntegerField(default=123456789),
            preserve_default=False,
        ),
    ]
