# Generated by Django 3.1 on 2020-09-10 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
        ('listings', '0006_auto_20200901_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing_model',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testapp.signup'),
            preserve_default=False,
        ),
    ]
